users:
  cud:
    general: 'users-stream'
  events:
    created: 'User.Created'
    updated: 'User.Updated'
tasks:
  be:
    assigned: 'task-assignee'
  events:
    assigned: 'Task.Assigned'
payments:
  be:
    created: 'payments'
  events:
    daily_payment_created: 'Payment.DailyPaymentCreated'
